### ISSUE TITLE
problem statement uploaded 

### ISSUE THREAD

**Issue by deemaalomair1** [deemaalomair1/CAS741_project#1]
I have uploaded the problem statements

**Comment by smiths** [comment]
Thank you @deemaalomair1 for your problem statement.  This is a good start.  However, I would like a second iteration.  In the new version, please address the following:

- Attention to detail in writing, punctuation, capitalization etc.  To help you with this, please go through my Writing Checklist (https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/BlankProjectTemplate/docs/Writing-Checklist.pdf)
- provide a simple stoichiometry example
- include a reference that describes the mass-mass stoichiometry problem - an on-line reference would be more convenient for me (and probably you), but it isn't required
- rather than say "The program", give your program a name
- mentioning the operating system is good, but please remove the reference to the programming language.  It is too early for that decision

In the future, when you create an issue, please include a link to the file (or folder) that needs to be reviewed, or include the commit hash of the commit that added the files that need to be reviewed.  It just saves the reviewer a bit of time.  :smile

**Comment by deemaalomair1** [comment]
Thanks Dr.Smith for your feedback. 
I uploaded the new version of the problem statement.

https://github.com/deemaalomair1/CAS741_project/tree/master/problem_statement

**Comment by smiths** [comment]
Thank you for the link @deemaalomair1.  Very convenient.  :smile:
There are still some grammar issues and lack of attention to detail issues with your problem statement, but the problem you define seems quite appropriate for CAS 741.  Your project is approved.  :smile:
