### ISSUE TITLE
Missing cite

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#14]
@deemaalomair1 
It seems like these two brackets should be referred to as reference resources.
![image](https://user-images.githubusercontent.com/55363335/67111111-3fddb080-f1a2-11e9-99ce-c6b7ff2bc318.png)

**Comment by sharyuwu** [comment]
@deemaalomair1 
One more suggestion about the cite.
If you can link Section(...) to the actual section, it can create a complete cross-reference to this document.
You can use /nameref{....} to achieve this goal!

**Comment by smiths** [comment]
@deemaalomair1, I think it would be good to follow the advice from @sharyuwu.  Please use BibTeX for citations, either showing the number of the citation in square brackets, or using the nat bib style (natural bibliography style).  @sharyuwu, since resolving these two issues involves different steps, when something like this comes up in the future, please create two separate issues.  It is easier to track changes that way.

**Comment by deemaalomair1** [comment]
Accepted and corrected in 173ef90

**Comment by smiths** [comment]
@deemaalomair1, your commit points to the pdf file that changed.  It is more helpful if you point to the commit that updated the tex file.
