### ISSUE TITLE
MIS semantic

### ISSUE THREAD

**Issue by deemaalomair1** [deemaalomair1/CAS741_project#41]
hello Dr.Smith , 

I tried to follow the steps you gave me to write my MIS document .. i came up with this new version. 

i defined an ADT and i modified the local functions , Access Routine Semantics.

i hope it is the right way to write the MIS. i found it hard because i did not attend the classes last week. 

https://github.com/deemaalomair1/CAS741_project/tree/master/docs/Design/MIS

Best regards,

**Comment by smiths** [comment]
@deemaalomair1, this is an improvement, but you still need to look over the examples that I sent to you.  You are not following the MIS template.  For instance, when export a type with a ?, that means that it is an ADT, which means it has to be documented in a template module.  I know it can be frustrating, but every word/symbol in the MIS has meaning.

I think ADTs in particular are confusing you.  I think you should have an ADT for ReactionT.  This wouldn't be in the module Input, but in a ReactionT module.  You can think of this as defining a class.  The reactions are objects of the ReactionT class.  For each ADT,  you need a constructor (constructors will use the keyword new, like in Java), and you will need access programs.  For ReactionT, I think you would have an isBalanced() method, or maybe just a Balance method.

You have an ElementT = ? in the AtomicMass module, but you don't define an interface for ElementT here.  Exports means that this is the module that defines the type.  You also wouldn't use an ADT for ElementT; it is too simple for that.   You just define ElementT with the set of elements.  (The way you have defined it on page 6 is wrong; it is just the set, the other for all stuff you have at the front isn't mathematically meaningful.)

Remember attention to detail, there are many incorrect spaces inserted in your expressions.  Please use the writing checklist and the MIS checklist to check your work.  

I see "if" in at least one of your expressions.  If you want an "if", use a conditional expression.

In some of your access program syntax tables you describe the exceptions in words.  You don't want to do this;  you want to give each exception a meaningful name and list the name here.  In the semantics section  you describe what causes this exception to occur, usually with a conditional rule.

Your atomic mass module has state variables listed, but no way to change the values of the state variables.  If you have state variables, there should be at least one transition.

**Comment by deemaalomair1** [comment]
Thank you Dr.Smith your comment is really helpful. 

i came up with new template module "ReactionT" and i added two methods as illustrated in the picture . but i do not fully understand if you mean that i do not need all the details added in module number 8 "MIS of chemical reaction balancing module" ? or i need two separate modules one for the ReationT and other for all the methods needed to get balanced reaction? 

![Screen Shot 2019-11-24 at 3 26 29 PM](https://user-images.githubusercontent.com/45468077/69501050-16b1ed80-0ecf-11ea-858d-cced33425cfc.png)

**Comment by smiths** [comment]
@deemaalomair1, there are many potential designs.  The approach that first comes to my mind is to make the ReactionT an Abstract Data Type.  In this case a reaction will know how to balance itself.  One version of this would be a reaction knows how to create a new balanced reaction from itself.  In the first case the reaction has a mutator, in the second it has an output.  The second approach is more the functional programming approach.  You can also have a design where the reaction is just data on the reaction, and another module has the algorithm for balancing the reaction.  Arguments can be made for either approach.  My instinct however is that an ADT for reactions, which know how to balance themselves, will be simpler, because inside the implementation of the module the secrets are known.

If you follow the reaction knowing how to balance itself approach, then you need improve your Reaction ADT.  When you look at the examples of ADTs in the course notes, you'll see that all ADTs have a constructor.  You don't have one.

**Comment by deemaalomair1** [comment]
got it. 

thank you Dr.Smith
